### PR TITLE
Race conditions when running multiple threads

### PR DESCRIPTION
**Pull request by michelole**
JOD Converter still has some race conditions that trigger when several threads request conversions at the same time.

This stress test helps to debug and identify such problems. It creates MAX_RUNNING_THREADS threads to concurrently request up to MAX_CONVERSIONS conversions from RTF to PDF. The threads races for 8 converters, which are restarted after MAX_TASKS_PER_PROCESS conversions each.

After some time running the test, the exception below occurs:

```
org.artofsolving.jodconverter.office.OfficeException: failed to restart
    at org.artofsolving.jodconverter.office.ManagedOfficeProcess.restartAndWait(ManagedOfficeProcess.java:99)
    at org.artofsolving.jodconverter.office.PooledOfficeManager$2.run(PooledOfficeManager.java:89)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: org.artofsolving.jodconverter.office.OfficeException: could not establish connection
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.artofsolving.jodconverter.office.ManagedOfficeProcess.restartAndWait(ManagedOfficeProcess.java:97)
    ... 6 more
Caused by: org.artofsolving.jodconverter.office.OfficeException: could not establish connection
    at org.artofsolving.jodconverter.office.ManagedOfficeProcess.doStartProcessAndConnect(ManagedOfficeProcess.java:162)
    at org.artofsolving.jodconverter.office.ManagedOfficeProcess.access$000(ManagedOfficeProcess.java:25)
    at org.artofsolving.jodconverter.office.ManagedOfficeProcess$3.run(ManagedOfficeProcess.java:93)
    ... 5 more
Caused by: java.lang.IllegalStateException: process with acceptString 'socket,host=127.0.0.1,port=2006' started but its pid could not be found
    at org.artofsolving.jodconverter.office.OfficeProcess.start(OfficeProcess.java:103)
    at org.artofsolving.jodconverter.office.OfficeProcess.start(OfficeProcess.java:64)
    at org.artofsolving.jodconverter.office.ManagedOfficeProcess.doStartProcessAndConnect(ManagedOfficeProcess.java:134)
    ... 7 more
```

I'm crossposting this pull request for nuxeo and xwiki repositories in the hope of someone helping fix the bug.

### CODE REVIEW

**Comment by jcarsique** [comment]
Thanks.
Your PR cannot be merged: it is based on the xwiki fork which includes sigar related commits and a few others we didn't merge. 
I'm looking at merging (almost) only your own commit "Adds a stress test to detect race conditions." into a dedicated working branch until a solution is found to fix that issue.

**Comment by michelole** [comment]
Yes, I noticed that your fork is different from xwiki's only after I requested the pull request. I could also fork the nuxeo repository and prepare a new PR if you want.

**Comment by jcarsique** [comment]
Don't worry, I pushed your changes on branch fix-stressTest

**Comment by jcarsique** [comment]
Note I'm not sure I could reproduce the issue running the test: it should expect the error and fail if it is not reproduced. In my case, I got a success after 1min running: 

```
PASSED: runParallelConversions
===============================================
Default test
Tests run: 1, Failures: 0, Skips: 0
```

**Comment by michelole** [comment]
The test framework seems to ignore any exceptions thrown in other threads. Unfortunately I could not catch them and force a failure.

Could you see any exceptions in the output?

**Comment by nxmatic** [comment]
You can set a default thread exception handler in your test for catching
the error condition unless jod is overriding it.

**Pull request closed without merging**
